services:
  - type: web
    name: ai-sense-backend
    env: node
    region: oregon
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
