import React, { useState } from "react";
import { 
  FolderGit2, 
  Cpu, 
  Activity, 
  ShieldCheck, 
  Download, 
  Plus, 
  ExternalLink, 
  CheckCircle2, 
  Clock 
} from "lucide-react";
import { useNavigate } from "react-router-dom";

export default function Projects() {
  const navigate = useNavigate();

  const [projectsList] = useState([
    {
      id: 1,
      name: "Smart Environment Monitor",
      board: "Arduino UNO Q",
      sensors: "DHT22, MQ-6, LDR",
      created: "2026-08-20",
      lastTest: "Today, 21:40",
      health: 91,
      status: "Healthy",
      issues: "1 minor anomaly (MQ-6 variance)",
      recommendation: "Check MQ-6 calibration & allow 10-min warm-up."
    },
    {
      id: 2,
      name: "6-Axis Robotics Motion Tracker",
      board: "Arduino UNO Q",
      sensors: "MPU6050, HC-SR04",
      created: "2026-08-18",
      lastTest: "Yesterday",
      health: 97,
      status: "Healthy",
      issues: "0 anomalies",
      recommendation: "System baseline operating optimal."
    },
    {
      id: 3,
      name: "Industrial Current & Load Diagnostics",
      board: "Arduino UNO Q",
      sensors: "ACS712, ACS712-20A",
      created: "2026-08-15",
      lastTest: "3 days ago",
      health: 84,
      status: "Warning",
      issues: "Zero-offset drift detected",
      recommendation: "Verify current sensor zero-point calibration."
    }
  ]);

  const downloadHardwareTestReport = (p) => {
    const reportText = `================================================
AI SENSE HARDWARE TEST REPORT
================================================
Project: ${p.name}
Board: ${p.board}
Sensors: ${p.sensors}
Created Date: ${p.created}
Last Test Executed: ${p.lastTest}
------------------------------------------------
Overall Hardware Health: ${p.health}% (${p.status})
Detected Issues: ${p.issues}
------------------------------------------------
AI Diagnosis & Recommendations:
${p.recommendation}
================================================
Generated by AI SENSE Platform • ${new Date().toLocaleString()}
================================================`;

    const blob = new Blob([reportText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `AI_SENSE_REPORT_${p.name.replace(/\s+/g, '_')}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      {/* ── HEADER ── */}
      <div className="flex flex-wrap items-center justify-between gap-4 bg-slate-900 border border-slate-800 p-6 rounded-2xl">
        <div>
          <h1 className="text-2xl font-extrabold text-white flex items-center gap-2">
            <FolderGit2 className="text-blue-500" /> My Hardware Projects
          </h1>
          <p className="text-xs text-gray-400 mt-1">Manage project workspaces, hardware configurations &amp; export test reports</p>
        </div>

        <button
          onClick={() => navigate("/run")}
          className="bg-blue-600 hover:bg-blue-700 text-white font-extrabold text-xs px-5 py-3 rounded-xl flex items-center gap-2 transition shadow-lg shadow-blue-600/20"
        >
          <Plus size={16} /> New Hardware Project
        </button>
      </div>

      {/* ── PROJECT CARDS GRID ── */}
      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
        {projectsList.map((p) => (
          <div key={p.id} className="bg-slate-900 border border-slate-800 p-6 rounded-2xl space-y-4 flex flex-col justify-between hover:border-blue-500/30 transition">
            
            <div className="space-y-3">
              <div className="flex justify-between items-start">
                <h3 className="text-base font-extrabold text-white leading-snug">{p.name}</h3>
                <span className="px-2.5 py-0.5 rounded-full text-[10px] font-extrabold border bg-emerald-500/10 text-emerald-400 border-emerald-500/30">
                  🟢 {p.health}%
                </span>
              </div>

              <div className="space-y-1.5 text-xs text-gray-300">
                <div className="flex items-center gap-2">
                  <Cpu size={14} className="text-blue-400" />
                  <span>Board: <strong>{p.board}</strong></span>
                </div>
                <div className="flex items-center gap-2">
                  <Activity size={14} className="text-indigo-400" />
                  <span>Sensors: <strong>{p.sensors}</strong></span>
                </div>
                <div className="flex items-center gap-2">
                  <Clock size={14} className="text-purple-400" />
                  <span>Last Test: <strong>{p.lastTest}</strong></span>
                </div>
              </div>

              <div className="p-3 rounded-xl bg-slate-950 border border-slate-800 text-[11px] text-gray-400 space-y-1">
                <div className="text-gray-300 font-bold">Diagnostics Summary:</div>
                <div>• Issues: {p.issues}</div>
              </div>
            </div>

            {/* Action Buttons */}
            <div className="grid grid-cols-2 gap-2 pt-2 border-t border-slate-800">
              <button
                onClick={() => navigate("/run")}
                className="bg-slate-950 hover:bg-slate-800 border border-slate-800 text-white text-xs font-bold py-2 rounded-xl flex items-center justify-center gap-1.5 transition"
              >
                <ExternalLink size={14} /> Open
              </button>

              <button
                onClick={() => navigate("/testing")}
                className="bg-blue-600/10 hover:bg-blue-600/20 border border-blue-500/30 text-blue-400 text-xs font-bold py-2 rounded-xl flex items-center justify-center gap-1.5 transition"
              >
                <Activity size={14} /> Test
              </button>

              <button
                onClick={() => navigate("/diagnostics")}
                className="bg-purple-600/10 hover:bg-purple-600/20 border border-purple-500/30 text-purple-400 text-xs font-bold py-2 rounded-xl flex items-center justify-center gap-1.5 transition col-span-2 sm:col-span-1"
              >
                <ShieldCheck size={14} /> Analyze
              </button>

              <button
                onClick={() => downloadHardwareTestReport(p)}
                className="bg-emerald-600/10 hover:bg-emerald-600/20 border border-emerald-500/30 text-emerald-400 text-xs font-bold py-2 rounded-xl flex items-center justify-center gap-1.5 transition col-span-2 sm:col-span-1"
              >
                <Download size={14} /> Report
              </button>
            </div>

          </div>
        ))}
      </div>
    </div>
  );
}